// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Container for submitting batches of transform graphs
    /// </summary>
    public partial class Batch
    {
        /// <summary>
        /// Initializes a new instance of the Batch class.
        /// </summary>
        public Batch()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Batch class.
        /// </summary>
        /// <param name="items">Collection of transform graphs for processing.
        /// Each item represents a single billable operation.</param>
        public Batch(IList<TransformGraph> items)
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets collection of transform graphs for processing. Each
        /// item represents a single billable operation.
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<TransformGraph> Items { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Items == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Items");
            }
            if (Items != null)
            {
                foreach (var element in Items)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
