// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for BatchStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BatchStatus
    {
        [EnumMember(Value = "pending")]
        Pending,
        [EnumMember(Value = "finished")]
        Finished
    }
    internal static class BatchStatusEnumExtension
    {
        internal static string ToSerializedValue(this BatchStatus? value)
        {
            return value == null ? null : ((BatchStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this BatchStatus value)
        {
            switch( value )
            {
                case BatchStatus.Pending:
                    return "pending";
                case BatchStatus.Finished:
                    return "finished";
            }
            return null;
        }

        internal static BatchStatus? ParseBatchStatus(this string value)
        {
            switch( value )
            {
                case "pending":
                    return BatchStatus.Pending;
                case "finished":
                    return BatchStatus.Finished;
            }
            return null;
        }
    }
}
