// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Converts source to grayscale.
    /// </summary>
    [Newtonsoft.Json.JsonObject("Image_Grayscale")]
    public partial class ImageGrayscale : TransformUnit
    {
        /// <summary>
        /// Initializes a new instance of the ImageGrayscale class.
        /// </summary>
        public ImageGrayscale()
        {
            CustomInit();
        }


        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
