// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Resize the image to a specific height. Width will depend on aspect
    /// ratio of image.
    /// </summary>
    [Newtonsoft.Json.JsonObject("Image_ResizeToHeight")]
    public partial class ImageResizeToHeight : TransformUnit
    {
        /// <summary>
        /// Initializes a new instance of the ImageResizeToHeight class.
        /// </summary>
        public ImageResizeToHeight()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImageResizeToHeight class.
        /// </summary>
        /// <param name="height">Output height</param>
        /// <param name="resizeKernel">The resampling algorithm used for
        /// resizing. Possible values include: 'lanczos3', 'lanczos2', 'cubic',
        /// 'nearest'</param>
        public ImageResizeToHeight(int height, ResizeKernel? resizeKernel = default(ResizeKernel?))
        {
            Height = height;
            ResizeKernel = resizeKernel;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets output height
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public int Height { get; set; }

        /// <summary>
        /// Gets or sets the resampling algorithm used for resizing. Possible
        /// values include: 'lanczos3', 'lanczos2', 'cubic', 'nearest'
        /// </summary>
        [JsonProperty(PropertyName = "resizeKernel")]
        public ResizeKernel? ResizeKernel { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
