// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Output to Tiff
    /// </summary>
    [Newtonsoft.Json.JsonObject("ImageFormat_Tiff")]
    public partial class ImageFormatTiff : TransformUnit
    {
        /// <summary>
        /// Initializes a new instance of the ImageFormatTiff class.
        /// </summary>
        public ImageFormatTiff()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImageFormatTiff class.
        /// </summary>
        /// <param name="quality">Tiff compression level</param>
        /// <param name="compression">Type of compression used in Tiff output.
        /// Possible values include: 'jpeg', 'deflate', 'lzw',
        /// 'ccittfax4'</param>
        /// <param name="predictor">Tiff compression predictor. Possible values
        /// include: 'horizontal', 'float', 'none'</param>
        public ImageFormatTiff(int? quality = default(int?), TiffCompression? compression = default(TiffCompression?), TiffPredictor? predictor = default(TiffPredictor?))
        {
            Quality = quality;
            Compression = compression;
            Predictor = predictor;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets tiff compression level
        /// </summary>
        [JsonProperty(PropertyName = "quality")]
        public int? Quality { get; set; }

        /// <summary>
        /// Gets or sets type of compression used in Tiff output. Possible
        /// values include: 'jpeg', 'deflate', 'lzw', 'ccittfax4'
        /// </summary>
        [JsonProperty(PropertyName = "compression")]
        public TiffCompression? Compression { get; set; }

        /// <summary>
        /// Gets or sets tiff compression predictor. Possible values include:
        /// 'horizontal', 'float', 'none'
        /// </summary>
        [JsonProperty(PropertyName = "predictor")]
        public TiffPredictor? Predictor { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Quality > 100)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Quality", 100);
            }
            if (Quality < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Quality", 1);
            }
        }
    }
}
