// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Resize image with touch-from-outside semantics with manual positioning
    /// of crop area via the gravity parameter.
    /// </summary>
    [Newtonsoft.Json.JsonObject("Image_ResizeCrop")]
    public partial class ImageResizeCrop : TransformUnit
    {
        /// <summary>
        /// Initializes a new instance of the ImageResizeCrop class.
        /// </summary>
        public ImageResizeCrop()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImageResizeCrop class.
        /// </summary>
        /// <param name="width">Output width</param>
        /// <param name="height">Output height</param>
        /// <param name="gravity">Position of crop area by gravity. Possible
        /// values include: 'center', 'centre', 'north', 'northeast', 'east',
        /// 'southeast', 'south', 'southwest', 'west', 'northwest'</param>
        /// <param name="resizeKernel">The resampling algorithm used for
        /// resizing. Possible values include: 'lanczos3', 'lanczos2', 'cubic',
        /// 'nearest'</param>
        public ImageResizeCrop(int width, int height, Gravity? gravity = default(Gravity?), ResizeKernel? resizeKernel = default(ResizeKernel?))
        {
            Width = width;
            Height = height;
            Gravity = gravity;
            ResizeKernel = resizeKernel;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets output width
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public int Width { get; set; }

        /// <summary>
        /// Gets or sets output height
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public int Height { get; set; }

        /// <summary>
        /// Gets or sets position of crop area by gravity. Possible values
        /// include: 'center', 'centre', 'north', 'northeast', 'east',
        /// 'southeast', 'south', 'southwest', 'west', 'northwest'
        /// </summary>
        [JsonProperty(PropertyName = "gravity")]
        public Gravity? Gravity { get; set; }

        /// <summary>
        /// Gets or sets the resampling algorithm used for resizing. Possible
        /// values include: 'lanczos3', 'lanczos2', 'cubic', 'nearest'
        /// </summary>
        [JsonProperty(PropertyName = "resizeKernel")]
        public ResizeKernel? ResizeKernel { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
