// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Change image colors to tinted monochrome
    /// </summary>
    [Newtonsoft.Json.JsonObject("Image_Tint")]
    public partial class ImageTint : TransformUnit
    {
        /// <summary>
        /// Initializes a new instance of the ImageTint class.
        /// </summary>
        public ImageTint()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImageTint class.
        /// </summary>
        /// <param name="tint">The tint color</param>
        public ImageTint(Color tint)
        {
            Tint = tint;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the tint color
        /// </summary>
        [JsonProperty(PropertyName = "tint")]
        public Color Tint { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Tint == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Tint");
            }
            if (Tint != null)
            {
                Tint.Validate();
            }
        }
    }
}
