// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ResizeKernel.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ResizeKernel
    {
        [EnumMember(Value = "lanczos3")]
        Lanczos3,
        [EnumMember(Value = "lanczos2")]
        Lanczos2,
        [EnumMember(Value = "cubic")]
        Cubic,
        [EnumMember(Value = "nearest")]
        Nearest
    }
    internal static class ResizeKernelEnumExtension
    {
        internal static string ToSerializedValue(this ResizeKernel? value)
        {
            return value == null ? null : ((ResizeKernel)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ResizeKernel value)
        {
            switch( value )
            {
                case ResizeKernel.Lanczos3:
                    return "lanczos3";
                case ResizeKernel.Lanczos2:
                    return "lanczos2";
                case ResizeKernel.Cubic:
                    return "cubic";
                case ResizeKernel.Nearest:
                    return "nearest";
            }
            return null;
        }

        internal static ResizeKernel? ParseResizeKernel(this string value)
        {
            switch( value )
            {
                case "lanczos3":
                    return ResizeKernel.Lanczos3;
                case "lanczos2":
                    return ResizeKernel.Lanczos2;
                case "cubic":
                    return ResizeKernel.Cubic;
                case "nearest":
                    return ResizeKernel.Nearest;
            }
            return null;
        }
    }
}
