// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Strategy.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Strategy
    {
        [EnumMember(Value = "attention")]
        Attention,
        [EnumMember(Value = "entropy")]
        Entropy
    }
    internal static class StrategyEnumExtension
    {
        internal static string ToSerializedValue(this Strategy? value)
        {
            return value == null ? null : ((Strategy)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Strategy value)
        {
            switch( value )
            {
                case Strategy.Attention:
                    return "attention";
                case Strategy.Entropy:
                    return "entropy";
            }
            return null;
        }

        internal static Strategy? ParseStrategy(this string value)
        {
            switch( value )
            {
                case "attention":
                    return Strategy.Attention;
                case "entropy":
                    return Strategy.Entropy;
            }
            return null;
        }
    }
}
