// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for TiffPredictor.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TiffPredictor
    {
        [EnumMember(Value = "horizontal")]
        Horizontal,
        [EnumMember(Value = "float")]
        Float,
        [EnumMember(Value = "none")]
        None
    }
    internal static class TiffPredictorEnumExtension
    {
        internal static string ToSerializedValue(this TiffPredictor? value)
        {
            return value == null ? null : ((TiffPredictor)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this TiffPredictor value)
        {
            switch( value )
            {
                case TiffPredictor.Horizontal:
                    return "horizontal";
                case TiffPredictor.Float:
                    return "float";
                case TiffPredictor.None:
                    return "none";
            }
            return null;
        }

        internal static TiffPredictor? ParseTiffPredictor(this string value)
        {
            switch( value )
            {
                case "horizontal":
                    return TiffPredictor.Horizontal;
                case "float":
                    return TiffPredictor.Float;
                case "none":
                    return TiffPredictor.None;
            }
            return null;
        }
    }
}
