// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A wrapped for RawTransformGraph instances, containing
    /// operation-specific metadata
    /// </summary>
    public partial class TransformGraphMetadataEnvelope
    {
        /// <summary>
        /// Initializes a new instance of the TransformGraphMetadataEnvelope
        /// class.
        /// </summary>
        public TransformGraphMetadataEnvelope()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransformGraphMetadataEnvelope
        /// class.
        /// </summary>
        /// <param name="graph">The transform graph that represents the
        /// operation</param>
        /// <param name="operationId">The operation id of this
        /// operation</param>
        /// <param name="batchId">The batch id of the batch containing this
        /// operation</param>
        /// <param name="accountId">The account id of the account that will
        /// be/was charged for this operation</param>
        /// <param name="ownerId">The user id of the user that submitted this
        /// batch</param>
        public TransformGraphMetadataEnvelope(TransformGraph graph = default(TransformGraph), System.Guid? operationId = default(System.Guid?), System.Guid? batchId = default(System.Guid?), System.Guid? accountId = default(System.Guid?), int? ownerId = default(int?))
        {
            Graph = graph;
            OperationId = operationId;
            BatchId = batchId;
            AccountId = accountId;
            OwnerId = ownerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the transform graph that represents the operation
        /// </summary>
        [JsonProperty(PropertyName = "graph")]
        public TransformGraph Graph { get; set; }

        /// <summary>
        /// Gets or sets the operation id of this operation
        /// </summary>
        [JsonProperty(PropertyName = "operationId")]
        public System.Guid? OperationId { get; set; }

        /// <summary>
        /// Gets or sets the batch id of the batch containing this operation
        /// </summary>
        [JsonProperty(PropertyName = "batchId")]
        public System.Guid? BatchId { get; set; }

        /// <summary>
        /// Gets or sets the account id of the account that will be/was charged
        /// for this operation
        /// </summary>
        [JsonProperty(PropertyName = "accountId")]
        public System.Guid? AccountId { get; set; }

        /// <summary>
        /// Gets or sets the user id of the user that submitted this batch
        /// </summary>
        [JsonProperty(PropertyName = "ownerId")]
        public int? OwnerId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Graph != null)
            {
                Graph.Validate();
            }
        }
    }
}
