// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pixelshift.Autorest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Target type for TransformUnits that are unrecognized at the current
    /// schema level
    /// </summary>
    [Newtonsoft.Json.JsonObject("Unit_Unknown")]
    public partial class UnitUnknown : TransformUnit
    {
        /// <summary>
        /// Initializes a new instance of the UnitUnknown class.
        /// </summary>
        public UnitUnknown()
        {
            CustomInit();
        }


        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
